name: /home/jaschneider/projects/DRG-CaSeg/.venv
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - _python_abi3_support=1.0
  - absl-py=2.3.1
  - alsa-lib=1.2.15.1
  - anyio=4.12.1
  - aom=3.9.1
  - argon2-cffi=25.1.0
  - argon2-cffi-bindings=25.1.0
  - arrow=1.4.0
  - asttokens=3.0.1
  - async-lru=2.0.5
  - attrs=25.4.0
  - av=14.2.0
  - babel=2.17.0
  - beautifulsoup4=4.14.3
  - bleach=6.3.0
  - bleach-with-css=6.3.0
  - blosc=1.21.6
  - bokeh=3.8.1
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.34.6
  - c-blosc2=2.15.2
  - ca-certificates=2026.1.4
  - cached-property=1.5.2
  - cached_property=1.5.2
  - caiman=1.13.0
  - cairo=1.18.4
  - certifi=2026.1.4
  - cffi=1.17.1
  - charls=2.4.2
  - charset-normalizer=3.4.4
  - colorama=0.4.6
  - colorcet=3.1.0
  - comm=0.2.3
  - contourpy=1.3.3
  - coverage=7.13.1
  - cpython=3.12.12
  - cycler=0.12.1
  - cyrus-sasl=2.1.28
  - dav1d=1.2.1
  - dbus=1.13.6
  - debugpy
  - decorator=5.2.1
  - defusedxml=0.7.1
  - deprecated=1.3.1
  - donfig=0.8.1.post1
  - double-conversion=3.3.1
  - exceptiongroup=1.3.1
  - executing=2.2.1
  - expat=2.7.3
  - ffmpeg=7.1.0
  - filelock=3.20.2
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fqdn=1.5.1
  - freeglut=3.2.2
  - freetype=2.14.1
  - fribidi=1.0.16
  - gdk-pixbuf=2.42.12
  - giflib=5.2.2
  - gmp=6.3.0
  - gmpy2=2.2.1
  - graphite2=1.3.14
  - h11=0.16.0
  - h2=4.3.0
  - h5py=3.13.0
  - harfbuzz=11.0.0
  - hdf5=1.14.3
  - hdmf=4.2.0
  - holoviews=1.22.1
  - hpack=4.1.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.11
  - imagecodecs=2024.9.22
  - imath=3.1.12
  - importlib-metadata=8.7.0
  - importlib_resources=6.5.2
  - iniconfig=2.3.0
  - ipykernel=7.1.0
  - ipyparallel=9.0.2
  - ipython=9.9.0
  - ipython_pygments_lexers=1.1.1
  - ipywidgets=8.1.8
  - isoduration=20.11.0
  - jasper=4.2.8
  - jedi=0.19.2
  - jinja2=3.1.6
  - json5=0.13.0
  - jsonpointer=3.0.0
  - jsonschema=4.26.0
  - jsonschema-specifications=2025.9.1
  - jsonschema-with-format-nongpl=4.26.0
  - jupyter=1.1.1
  - jupyter-lsp=2.3.0
  - jupyter_bokeh=4.0.5
  - jupyter_client=8.7.0
  - jupyter_console=6.6.3
  - jupyter_core=5.9.1
  - jupyter_events=0.12.0
  - jupyter_server=2.17.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.5.1
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.28.0
  - jupyterlab_widgets=3.0.16
  - jxrlib=1.1
  - keras=3.11.2
  - keyutils=1.6.3
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lame=3.100
  - lark=1.3.1
  - lazy-loader=0.4
  - lcms2=2.17
  - ld_impl_linux-64=2.44
  - lerc=4.0.0
  - libabseil=20240722.0
  - libaec=1.1.4
  - libasprintf=0.25.1
  - libass=0.17.3
  - libavif16=1.1.1
  - libblas=3.11.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.11.0
  - libclang-cpp19.1=19.1.7
  - libclang13=19.1.7
  - libcrc32c=1.1.2
  - libcups=2.3.3
  - libcurl=8.18.0
  - libde265=1.0.15
  - libdeflate=1.22
  - libdrm=2.4.125
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libev=4.33
  - libexpat=2.7.3
  - libffi=3.4.4
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgettextpo=0.25.1
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libgl=1.7.0
  - libglib=2.84.0
  - libglu=9.0.3
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.2.0
  - libheif=1.19.6
  - libhwloc=2.11.2
  - libhwy=1.3.0
  - libiconv=1.18
  - libjpeg-turbo=3.1.2
  - libjxl=0.11.1
  - liblapack=3.11.0
  - liblapacke=3.11.0
  - libllvm19=19.1.7
  - libnghttp2=1.67.0
  - libnsl=2.0.0
  - libntlm=1.8
  - libopenblas=0.3.30
  - libopencv=4.10.0
  - libopengl=1.7.0
  - libopenvino=2024.4.0
  - libopenvino-auto-batch-plugin=2024.4.0
  - libopenvino-auto-plugin=2024.4.0
  - libopenvino-hetero-plugin=2024.4.0
  - libopenvino-intel-cpu-plugin=2024.4.0
  - libopenvino-intel-gpu-plugin=2024.4.0
  - libopenvino-intel-npu-plugin=2024.4.0
  - libopenvino-ir-frontend=2024.4.0
  - libopenvino-onnx-frontend=2024.4.0
  - libopenvino-paddle-frontend=2024.4.0
  - libopenvino-pytorch-frontend=2024.4.0
  - libopenvino-tensorflow-frontend=2024.4.0
  - libopenvino-tensorflow-lite-frontend=2024.4.0
  - libopus=1.6
  - libpciaccess=0.18
  - libpng=1.6.53
  - libpq=17.7
  - libprotobuf=5.28.2
  - librsvg=2.58.4
  - libsodium=1.0.20
  - libsqlite=3.51.1
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libtiff=4.7.0
  - libtorch=2.5.1
  - libuuid=2.41.3
  - libuv=1.51.0
  - libva=2.22.0
  - libvpx=1.14.1
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.8.0
  - libxml2=2.13.5
  - libxslt=1.1.39
  - libzlib=1.3.1
  - libzopfli=1.0.3
  - linkify-it-py=2.0.3
  - lz4-c=1.9.4
  - markdown=3.10
  - markdown-it-py=4.0.0
  - markupsafe=3.0.3
  - matplotlib-base=3.10.8
  - matplotlib-inline=0.2.1
  - mdit-py-plugins=0.5.0
  - mdurl=0.1.2
  - mistune=3.2.0
  - ml_dtypes=0.5.4
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - msgpack-python=1.1.2
  - munkres=1.1.4
  - mypy=1.19.1
  - mypy_extensions=1.1.0
  - mysql-common=9.0.1
  - mysql-libs=9.0.1
  - namex=0.1.0
  - narwhals=2.15.0
  - nbclient=0.10.4
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - nomkl=1.0
  - notebook=7.5.1
  - notebook-shim=0.2.4
  - numcodecs=0.16.5
  - numpy=1.26.4
  - ocl-icd=2.3.3
  - opencl-headers=2025.06.13
  - opencv=4.10.0
  - openexr=3.3.2
  - openh264=2.5.0
  - openjpeg=2.5.3
  - openldap=2.6.10
  - openssl=3.6.0
  - optree=0.18.0
  - overrides=7.7.0
  - packaging=25.0
  - pandas=2.3.3
  - pandocfilters=1.5.0
  - panel=1.8.5
  - pango=1.56.3
  - param=2.3.1
  - parso=0.8.5
  - pathspec=1.0.2
  - pcre2=10.44
  - peakutils=1.3.5
  - pexpect=4.9.0
  - pillow=11.3.0
  - pims=0.7
  - pip=25.3
  - pixman=0.46.4
  - platformdirs=4.5.1
  - pluggy=1.6.0
  - prometheus_client=0.23.1
  - prompt-toolkit=3.0.52
  - prompt_toolkit=3.0.52
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pugixml=1.14
  - pure_eval=0.2.3
  - py-opencv=4.10.0
  - pycparser=2.22
  - pygments=2.19.2
  - pynwb=3.1.3
  - pyqtgraph=0.14.0
  - pyside6=6.8.2
  - pysocks=1.7.1
  - pytest=9.0.2
  - pytest-cov=7.0.0
  - python=3.12.0
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.21.2
  - python-gil=3.12.12
  - python-json-logger=2.0.7
  - python-librt=0.7.7
  - python-tzdata=2025.3
  - python_abi=3.12
  - pytorch=2.5.1
  - pytz=2025.2
  - pyviz_comms=3.0.6
  - pyyaml=6.0.3
  - pyzmq=27.1.0
  - qhull=2020.2
  - qt6-main=6.8.2
  - rav1e=0.6.6
  - readline=8.3
  - referencing=0.37.0
  - requests=2.32.5
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rfc3987-syntax=1.1.0
  - rich=14.2.0
  - rpds-py=0.30.0
  - ruamel.yaml=0.19.1
  - ruamel.yaml.clib=0.2.15
  - scipy=1.16.3
  - send2trash=2.0.0
  - setuptools=80.9.0
  - six=1.17.0
  - sleef=3.9.0
  - slicerator=1.1.0
  - snappy=1.2.2
  - sniffio=1.3.1
  - soupsieve=2.8.1
  - sqlite=3.51.1
  - stack_data=0.6.3
  - svt-av1=2.3.0
  - sympy=1.14.0
  - tbb=2022.1.0
  - terminado=0.18.1
  - threadpoolctl=3.6.0
  - tinycss2=1.5.1
  - tk=8.6.15
  - tomli=2.3.0
  - torchvision=0.20.1
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - typing_utils=0.1.0
  - uc-micro-py=1.0.3
  - unicodedata2=17.0.0
  - uri-template=1.3.0
  - urllib3=2.5.0
  - wayland=1.23.1
  - wayland-protocols=1.47
  - wcwidth=0.2.14
  - webcolors=25.10.0
  - webencodings=0.5.1
  - websocket-client=1.9.0
  - wheel=0.45.1
  - widgetsnbextension=4.0.15
  - wrapt=1.17.3
  - x264=1!164.3095
  - x265=3.5
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.6
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.46
  - xmltodict=1.0.2
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxcursor=1.2.3
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.2
  - xorg-libxi=1.8.2
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.6
  - xorg-xorgproto=2024.1
  - xyzservices=2025.11.0
  - xz=5.6.4
  - yaml=0.2.5
  - zarr=3.1.5
  - zeromq=4.3.5
  - zfp=1.0.1
  - zipp=3.23.0
  - zlib=1.3.1
  - zlib-ng=2.2.5
  - zstandard=0.25.0
  - zstd=1.5.7
  - pip
  - pip:
      - alabaster==1.0.0
      - click==8.3.1
      - cloudpickle==3.1.2
      - colorlog==6.10.1
      - cython==3.2.4
      - czifile==2019.7.2.1
      - dask==2025.11.0
      - dask-glm==0.3.2
      - dask-ml==2025.1.0
      - distributed==2025.11.0
      - docutils==0.22.4
      - fonttools==4.60.1
      - fsspec==2025.10.0
      - google-crc32c==1.7.1
      - imageio==2.37.2
      - imageio-ffmpeg==0.6.0
      - imagesize==1.4.1
      - joblib==1.5.2
      - llvmlite==0.45.1
      - locket==1.0.0
      - matplotlib==3.10.7
      - moviepy==2.2.1
      - multipledispatch==1.0.0
      - networkx==3.5
      - numba==0.62.1
      - numpydoc==1.10.0
      - opencv-python==4.12.0.88
      - partd==1.4.2
      - proglog==0.1.12
      - psutil==7.1.3
      - pyarrow==22.0.0
      - pyparsing==3.2.5
      - python-dotenv==1.2.1
      - roman-numerals==4.1.0
      - scikit-image==0.25.2
      - scikit-learn==1.7.2
      - seaborn==0.13.2
      - snowballstemmer==3.0.1
      - sortedcontainers==2.4.0
      - sparse==0.17.0
      - sphinx==9.1.0
      - sphinxcontrib-applehelp==2.0.0
      - sphinxcontrib-devhelp==2.0.0
      - sphinxcontrib-htmlhelp==2.1.0
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==2.0.0
      - sphinxcontrib-serializinghtml==2.0.0
      - tblib==3.2.2
      - tifffile==2025.10.4
      - toolz==1.1.0
      - tornado==6.5.2
      - tzdata==2025.2
      - yapf==0.43.0
      - zict==3.0.0
prefix: /home/jaschneider/projects/DRG-CaSeg/.venv
